spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus
spring.main.allow-bean-definition-overriding=true

# Security Configuration
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email
