spring.data.mongodb.uri=mongodb://chandragamage88_db_user:it22280374MERNITPM@ac-yk7zv7j-shard-00-00.1ggxriv.mongodb.net:27017,ac-yk7zv7j-shard-00-01.1ggxriv.mongodb.net:27017,ac-yk7zv7j-shard-00-02.1ggxriv.mongodb.net:27017/smartcampus?ssl=true&replicaSet=atlas-qgnxyw-shard-0&authSource=admin&appName=Cluster0
spring.main.allow-bean-definition-overriding=true

# Security Configuration
jwt.secret=uninexus_secret_key_2026_safe
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email
